---
galaxy_info:
  author: wtferris
  description: Interact with the dbahub package API
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - all
dependencies: []
